/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as DashboardRouteImport } from './routes/_dashboard';
import { Route as SignInRouteImport } from './routes/sign-in';
import { Route as SignUpRouteImport } from './routes/sign-up';
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sign-in': typeof SignInRoute;
  '/sign-up': typeof SignUpRoute;
  '/home': typeof DashboardHomeRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sign-in': typeof SignInRoute;
  '/sign-up': typeof SignUpRoute;
  '/home': typeof DashboardHomeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_dashboard': typeof DashboardRouteWithChildren;
  '/sign-in': typeof SignInRoute;
  '/sign-up': typeof SignUpRoute;
  '/_dashboard/home': typeof DashboardHomeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/home';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/sign-in' | '/sign-up' | '/home';
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/_dashboard/home';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  SignUpRoute: typeof SignUpRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_dashboard': {
      id: '/_dashboard';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sign-in': {
      id: '/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sign-up': {
      id: '/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_dashboard/home': {
      id: '/_dashboard/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof DashboardHomeRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
